#!/usr/bin/env python3
import sys
import pprint
from collections import OrderedDict  # Glömde importera OrderedDict

alternativ = {
    "helpdesk": ["helpdesk_mgmt", "helpdesk_mgmt_sale", "helpdesk_mgmt_timesheet"],
    "knowledge": ["document_page", "document_knowledge"],
    "account_followup": ["document_page", "document_knowledge"], ## TODO
}

nix = ['web_studio']

if len(sys.argv) < 2:
    print(f"Usage: {sys.argv[0]} path/to/__manifest__.py")
    sys.exit(1)

manifest_files = sys.argv[1:]


for manifest_file in manifest_files:
    with open(manifest_file, "r", encoding="utf-8") as f:
        code = f.read()

    manifest_dict = eval(code, {"__builtins__": None}, {})

    old_depends = manifest_dict.get('depends', [])
    new_depends = []
    for mod in old_depends:
        if mod in nix:
            continue
        if mod in alternativ and alternativ[mod] and alternativ[mod][0] != "":
            new_depends.extend(alternativ[mod])
        else:
            new_depends.append(mod)

    manifest_dict['depends'] = new_depends
    manifest_dict['license'] = 'AGPL-3'
    if 'author' in manifest_dict:
        manifest_dict['author'] = f"{manifest_dict['author']}, Vertel AB"
    else:
        manifest_dict['author'] = "Vertel AB"

    def order_manifest(manifest):
        prioritized_keys = ['name', 'version', 'category', 'depends', 'data', 'demo']
        ordered = OrderedDict()
        for key in prioritized_keys:
            if key in manifest:
                ordered[key] = manifest[key]
        for key in manifest:
            if key not in ordered:
                ordered[key] = manifest[key]
        return ordered

    ordered_manifest = order_manifest(manifest_dict)

    def format_manifest(ordered_manifest, indent=4):
        spaces = ' ' * indent
        lines = ['{']
        for key, value in ordered_manifest.items():
            formatted_value = pprint.pformat(value, indent=indent + 4, width=120)
            # Indentera värdet lite extra och placera på ny rad
            value_lines = formatted_value.splitlines()
            if len(value_lines) > 1:
                value_formatted = '\n' + '\n'.join(spaces + '    ' + line for line in value_lines)
            else:
                value_formatted = ' ' + value_lines[0]
            lines.append(f"{spaces!s}'{key}':{value_formatted},")
        lines.append('}')
        return '\n'.join(lines)

    with open(manifest_file, "w", encoding="utf-8") as f:
        f.write("# -*- coding: utf-8 -*-\n")
        f.write("# -*- manifest.py auto-generated by script -*-\n\n")
        f.write(format_manifest(ordered_manifest))
        f.write("\n")

    print(f"Manifestfilen '{manifest_file}' har uppdaterats med nya depends.")
